---
title: NicoStilo Barbershop
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: Nicostilobarbershop@hotmail.com
description: 'Public website for NicoStilo Barbershop

'
baseurl: 
url: nicostilobarbershop.com
twitter_username: jekyllrb
github_username: Nicostilo08
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
